---
kind: Service
apiVersion: v1
metadata: 
  # minikube service nodeapp-service --url
  # kubectl get deployment nodeapp-service -o yaml > nodeapp-service_result.yaml
  name: nodeapp-service
  labels:
    run: nodejs-app
spec:
  selector:
    run: nodejs-app
  ports:
    - # port accessible inside cluster
      port: 80
      # port to forward inside the pod
      targetPort: 4000
      # port accessible outside cluster
      nodePort: 30004
  type: LoadBalancer

---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: nodeapp-service
  labels:
    app: nodejs-app
spec:
  selector:
    matchLabels:
      run: nodejs-app
  replicas: 3
  template:
    metadata:
      labels:
        run: nodejs-app
    spec:
      containers:
        - name: nodeapp-container
          image: erikh111/nodejs-app:latest
          # image: npm/tests:local
          imagePullPolicy: Always
          ports:
            - containerPort: 4000

